name: Make Philo on push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test Make phi
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd ./philo && make
