name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make main
    - run: cd ./philo
    - run: make
    - run: make fclean
  
    - name: make bonus
    - run: cd ./philo_bonus
    - run: make
    - run: make fclean
